### ISSUE TITLE
engineio.client - packet queue is empty, aborting

### ISSUE THREAD

**Issue by BEEFY-JOE** [mmattDonk/AI-TTS-Donations#210]
Every 30 seconds Engine.IO connection drops and then reconnects. 

This is with StreamElements selected in the config.json

This does not happen with Channel_Points in the config.json

---------------------------------------------------------------------------------------------------------------------------------

21:49:50 ERROR    engineio.client - packet queue is empty, aborting                                                   client.py:663
         INFO     root - Engine.IO connection dropped                                                                 client.py:718
         INFO     root - Connection failed, new attempt in 0.95 seconds                                               client.py:652
21:49:51 INFO     root - Engine.IO connection established                                                             client.py:681
         INFO     root - Namespace / is connected                                                                     client.py:562
         INFO     root - Emitting event "authenticate" [/]                                                            client.py:395
         INFO     root - Reconnection successful                                                                      client.py:669
         INFO     root - Received event "authenticated" [/]                                                           client.py:580
         INFO     root - StreamElements connected!                                                                       bot.py:563
         
         
![image](https://user-images.githubusercontent.com/6415889/171549368-72e2c50c-2f06-4fad-b6dc-300d1fc57824.png)

**Comment by mmattbtw** [comment]
closing in favor for v5
