### ISSUE TITLE
multiple voice in one message support

### ISSUE THREAD

**Issue by MrAuro** [mmattDonk/AI-TTS-Donations#23]
maybe do multiple API requests at the same time, find the length of each voice and wait that much time before playing the next sound ApuThink

**Comment by mmattbtw** [comment]
i'm pretty sure the `playsound` function just waits until the sound is done playing before executing everything after it, so just doing:

- multiple api requests
- downloading all the mp3s from the requests
- put all the file names in a list
- for file in list: playsound
