### ISSUE TITLE
Make the project translation friendly

### ISSUE THREAD

**Issue by mopoIo** [mmattDonk/AI-TTS-Donations#233]
I wouldn't think of it as a priority but it would definitely make it futureproof

**Comment by mmattbtw** [comment]
Agreed, however recently I have been thinking about discontinuing the Python app in favor of a webapp, which will make translations and localization MUCH easier (with a library like Crowdin). May or may not happen, not sure.

I did see your fork however, if you'd like I'd be down for you to PR the repo to the README if you'd like.

**Comment by mopoIo** [comment]
Up to you 😁

**Comment by mmattbtw** [comment]
Go ahead, make the PR and I'll merge :^)

**Comment by mmattbtw** [comment]
v5 now has proper translation support: https://translate.solrock.mmattdonk.com/
