### ISSUE TITLE
An overlay that syncs to the voice that is playing

### ISSUE THREAD

**Issue by mopoIo** [mmattDonk/AI-TTS-Donations#253]
Could be fun to have custom in sync images to voices like this one https://fakeyou.com/w2l/WT:7k5d07dcz6yk3qp2pkj3zsg4jpq71 that played depending on the voice that is playing

**Comment by mmattbtw** [comment]
I don't believe there is any way to do this programmatically at the moment.

**Comment by mopoIo** [comment]
even if it wasn't custom generated? just that clip playing during the duration of the voice clip?

**Comment by mmattbtw** [comment]
@mopoIo i'd rather that be on the streamer, there is probably already other software to do that. i want to stick to audio only rn
