### ISSUE TITLE
make an automated setup process

### ISSUE THREAD

**Issue by mmattbtw** [mmattDonk/AI-TTS-Donations#53]
kinda like `setup.py` from [TwitchTunes](https://github.com/mmattDonk/TwitchTunes), ooh maybe a website to generate a config.json and .env?

**Comment by 12beesinatrenchcoat** [comment]
> maybe a website to generate a config.json and .env

If you need/want any help with that, I'd like to try my hand at that... :eyes:

**Comment by mmattbtw** [comment]
go ahead if you'd like :D

**Comment by 12beesinatrenchcoat** [comment]
update: working on it now, although it'll probably just be more of an interactive guide (no idea how to automatically fetch api keys)

**Comment by 12beesinatrenchcoat** [comment]
Hey, so, if I was to open a pull request for this, should I merge it into master (in a `docs/` directory) or under a `gh-pages` branch? (Assuming you'd use GitHub pages to host the thing.)

**Comment by mmattbtw** [comment]
I'd prefer a separate branch -- Will create the branch now.

**Comment by mmattbtw** [comment]
Closed #63
