### ISSUE TITLE
Custom voice prefix

### ISSUE THREAD

**Issue by mopoIo** [mmattDonk/AI-TTS-Donations#91]
Instead of having the uberduck model name, it could be handy to have a way to have custom prefixes for voices, for example:
`narrator=fate-ur-ts-tck-narrator` this way it would recognize `narrator: message` as `fate-ur-ts-tck-narrator: message`

**Comment by mopoIo** [comment]
fakeyou.com support could be very useful if we had a voice prefix option, since they allow private voices

**Comment by mmattbtw** [comment]
finally lol
